/** All UI copy in one place (Bahasa Malaysia added later as strings/ms.ts with the same shape). */
export const en = {
  appName: 'OutletBooking',
  tagline: 'Bookings, payments and your team in one app.',
  common: {
    retry: 'Try again',
    loading: 'Loading…',
    genericError: 'Something went wrong. Please try again.',
    networkError: "Can't reach the server. Check your connection and that the API is running.",
    comingSoon: 'Coming soon',
    logout: 'Log out',
    continue: 'Continue',
    back: 'Back',
  },
  login: {
    title: 'Welcome back',
    email: 'Email',
    password: 'Password',
    keepLoggedIn: 'Keep me logged in',
    forgot: 'Forgot password?',
    submit: 'Log in',
    staffNote: "Staff: log in with the email your business owner invited. You'll see your own schedule.",
    newHere: 'New to OutletBooking?',
    startTrial: 'Start 7-day free trial',
    invalid: 'Wrong email or password.',
  },
  signup: {
    step: (n: number) => `Step ${n} of 3`,
    accountTitle: 'Create your account',
    name: 'Your name',
    email: 'Email',
    phone: 'Mobile number',
    phoneHint: 'e.g. 012-345 6789',
    password: 'Password',
    passwordHint: 'At least 8 characters',
    businessTitle: 'Set up your business',
    businessName: 'Business name',
    bookingLink: 'Your booking link',
    available: 'Available',
    taken: 'Already taken',
    invalidSlug: '3–50 letters, numbers or dashes',
    checking: 'Checking…',
    kind: 'What kind of business?',
    trialNote: '7-day free trial · no card needed',
    haveAccount: 'Already have an account?',
    login: 'Log in',
  },
  templates: {
    real_estate: { title: 'Real estate viewing', sub: 'Book by agent' },
    vehicle_inspection: { title: 'Vehicle inspection', sub: 'Book by bay' },
    sports: { title: 'Sports courts', sub: 'Book by court' },
    workshop: { title: 'Workshop', sub: 'Book by bay' },
    barber_salon: { title: 'Barber / Salon', sub: 'Book by stylist' },
    other: { title: 'Other', sub: 'Clinic, tuition, more' },
  },
  forgot: {
    title: 'Reset password',
    body: 'Password reset by email is coming soon. For now, contact support to reset your password.',
    backToLogin: 'Back to log in',
  },
  today: {
    trial: (days: number) => `Free trial · ${days} ${days === 1 ? 'day' : 'days'} left`,
    trialEnded: 'Free trial ended',
    choosePlan: 'Choose a plan',
    bookingsToday: 'Bookings today',
    expectedRevenue: 'Expected revenue',
    checkedIn: 'Checked in',
    noShow: 'No-show',
    newBooking: 'New booking',
    walkIn: 'Walk-in',
    shareLink: 'Share link',
    upNext: 'Up next',
    seeCalendar: 'See calendar',
    emptyTitle: 'No bookings yet',
    emptyBody: 'Share your booking link so customers can book you 24/7.',
    shareMessage: (name: string, url: string) => `Book ${name} online: ${url}`,
  },
  tabs: {
    today: 'Today',
    calendar: 'Calendar',
    bookings: 'Bookings',
    setup: 'Setup',
    reports: 'Reports',
    schedule: 'Schedule',
    profile: 'Profile',
  },
  setup: {
    title: 'Setup',
    yourBusiness: 'Your business',
    account: 'Account',
    save: 'Save',
    saved: 'Saved',
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    archive: 'Archive',
    hidden: 'Hidden',
    inactive: 'Inactive',
    all: 'All',
    menu: {
      profile: 'Business profile',
      profileSub: 'Name, contact details, booking rules',
      services: 'Services & pricing',
      servicesSub: (n: number) => (n === 1 ? '1 service' : `${n} services`),
      resources: (label: string) => `${label}s & working hours`,
      resourcesSub: (n: number) => (n === 0 ? 'None yet — add one to take bookings' : `${n} set up`),
      timeOff: 'Time off & closures',
      timeOffSub: 'Public holidays, leave, maintenance',
      fields: 'Booking form questions',
      fieldsSub: (n: number) => (n === 1 ? '1 extra question' : `${n} extra questions`),
      staff: 'Staff',
      staffSub: 'Invite your team and link them to their schedule',
      bookingOff: 'Online booking is paused',
    },
    profile: {
      title: 'Business profile',
      details: 'Details',
      name: 'Business name',
      phone: 'Phone',
      whatsapp: 'WhatsApp number',
      whatsappHint: 'Customers tap this to message you',
      email: 'Email',
      address: 'Address',
      description: 'About your business',
      descriptionHint: 'Shown on your booking page',
      resourceLabel: 'What do customers book?',
      resourceLabelHint: 'e.g. Court, Bay, Agent, Room',
      rules: 'Booking rules',
      slotInterval: 'Start times every',
      minAdvance: 'Earliest booking',
      minAdvanceHint: 'How soon before the start a customer can book',
      maxDaysAhead: 'Book up to (days ahead)',
      cancelCutoff: 'Customers can cancel up to',
      bookingEnabled: 'Accept online bookings',
      bookingEnabledHint: 'Turn off to pause your booking page',
      none: 'No limit',
      before: (label: string) => `${label} before`,
    },
    services: {
      title: 'Services & pricing',
      newTitle: 'New service',
      editTitle: 'Edit service',
      empty: 'No services yet',
      emptyBody: 'Add what customers can book, with duration and price.',
      add: 'Add service',
      name: 'Service name',
      description: 'Description',
      block: 'Duration',
      blockHint: 'Length of one booking (or one block when customers choose)',
      customMin: 'Minutes',
      choose: 'Customer can choose',
      chooseHint: 'Leave all off for a fixed duration',
      priceUnit: 'Price',
      perBooking: 'Per booking',
      perBlock: 'Per block',
      price: 'Price',
      pricePerBlock: (d: string) => `Price per ${d}`,
      peak: 'Peak pricing',
      addRule: '+ Add rule',
      noRules: 'Same price all week',
      ruleTitle: 'Peak price rule',
      ruleName: 'Name',
      ruleDays: 'Days',
      ruleFrom: 'From',
      ruleTo: 'To',
      rulePrice: 'Peak price',
      ruleSave: 'Add rule',
      ruleDaysError: 'Pick at least one day',
      ruleTimeError: 'End must be after start',
      payment: 'Payment to confirm',
      payFull: 'Full payment upfront',
      payDeposit: 'Deposit only',
      payDepositHint: '· set amount',
      payVenue: 'Pay at venue',
      deposit: 'Deposit amount',
      location: 'Where does it happen?',
      atBusiness: 'At my business',
      atCustomer: "At the customer's location",
      atCustomerHint: 'Customer enters an address (viewings, mobile inspection)',
      buffer: 'Buffer after (min)',
      bufferHint: 'Clean-up or rest time after each booking',
      travelBuffer: 'Travel time (min)',
      travelBufferHint: 'Blocked before and after for travel',
      visible: 'Show on booking page',
      resources: (label: string) => `${label}s that offer this`,
      noResources: (label: string) => `Add a ${label.toLowerCase()} first, then assign it here.`,
      save: 'Save service',
      archiveTitle: 'Archive this service?',
      archiveBody: 'It will be removed from your booking page. Past bookings are kept.',
      perBlockShort: '/block',
    },
    resources: {
      title: (label: string) => `${label}s & working hours`,
      labelNote: 'Label set by your template · rename in Business profile',
      newTitle: (label: string) => `New ${label.toLowerCase()}`,
      empty: (label: string) => `No ${label.toLowerCase()}s yet`,
      emptyBody: 'Add what customers book, then set its working hours.',
      add: (label: string) => `Add ${label.toLowerCase()}`,
      name: 'Name',
      type: 'Type',
      types: { staff: 'Staff', bay: 'Bay', court: 'Court', room: 'Room', property: 'Property', other: 'Other' },
      active: 'Taking bookings',
      services: 'Services offered',
      linkedStaff: 'Linked staff login',
      noLinkedStaff: 'Not linked',
      hours: 'Working hours',
      closed: 'Closed',
      addBreak: '+ Add hours',
      copyHours: (label: string) => `Copy these hours to other ${label.toLowerCase()}s`,
      copyTitle: 'Copy working hours',
      copyBody: (label: string) => `Replaces the working hours of the selected ${label.toLowerCase()}s.`,
      copyDone: 'Hours copied',
      saveHours: 'Save hours',
      hoursSaved: 'Working hours saved',
      save: 'Save',
      createFirst: 'Save first, then set working hours.',
      archiveTitle: (label: string) => `Archive this ${label.toLowerCase()}?`,
      archiveBody: 'It stops taking bookings and frees a slot on your plan. Past bookings are kept.',
      timeOff: 'Time off & closures',
      noHours: 'No working hours set',
      limitReached: 'You have reached your plan limit.',
    },
    timeOff: {
      title: 'Time off & closures',
      empty: 'No upcoming time off',
      emptyBody: 'Add public holidays, leave or maintenance so nobody can book then.',
      add: '+ Add',
      newTitle: 'Add time off',
      appliesTo: 'Applies to',
      wholeBusiness: 'Whole business',
      from: 'From',
      to: 'To',
      allDay: 'All day',
      startTime: 'Start time',
      endTime: 'End time',
      reason: 'Reason (optional)',
      reasonHint: 'e.g. Hari Raya, resurfacing, annual leave',
      save: 'Add time off',
      deleteTitle: 'Delete this time off?',
      deleteBody: 'Customers will be able to book this time again.',
      rangeError: 'End must be after start',
      allLabel: 'All',
    },
    fields: {
      title: 'Booking form questions',
      intro: 'Customers answer these when booking. Name and phone are always asked.',
      empty: 'No extra questions',
      emptyBody: 'Add questions like plate number or number of players.',
      add: '+ Add',
      newTitle: 'New question',
      editTitle: 'Edit question',
      label: 'Question',
      key: 'Field key',
      keyHint: 'Used in reports and search. Changing it hides old answers from search.',
      type: 'Answer type',
      types: { text: 'Text', number: 'Number', select: 'Dropdown', date: 'Date', address: 'Address', phone: 'Phone' },
      options: 'Dropdown options',
      addOption: '+ Add option',
      optionPlaceholder: (n: number) => `Option ${n}`,
      required: 'Required',
      searchable: 'Searchable',
      searchableHint: 'Find bookings by this answer (e.g. plate number)',
      active: 'Show on booking form',
      appliesTo: 'Ask for',
      allServices: 'All services',
      save: 'Save question',
      deleteTitle: 'Delete this question?',
      deleteBody: 'Answers already given stay on past bookings.',
      moveUp: 'Move up',
      moveDown: 'Move down',
      requiredTag: 'Required',
    },
  },
  staff: {
    title: 'Staff',
    team: 'Your team',
    pending: 'Invitations waiting',
    invite: 'Invite staff',
    inviteTitle: 'Invite a staff member',
    inviteBody: "They get a link to create their login. You'll share it by WhatsApp, email or SMS.",
    email: 'Their email',
    linkTo: (label: string) => `Their ${label.toLowerCase()} (optional)`,
    linkHint: 'Staff only see bookings for what is linked to them',
    none: 'None',
    send: 'Create invite link',
    shareMessage: (business: string, url: string) =>
      `You're invited to join ${business} on OutletBooking. Tap to set up your staff login: ${url}`,
    share: 'Share link',
    revokeTitle: 'Cancel this invitation?',
    revokeBody: 'The link will stop working.',
    revoke: 'Cancel invite',
    expires: (date: string) => `Link valid until ${date}`,
    owner: 'Owner',
    staffRole: 'Staff',
    inactive: 'No access',
    empty: 'Just you so far',
    emptyBody: 'Invite staff so they can see their own schedule and check customers in.',
    memberTitle: 'Staff access',
    active: 'Can log in',
    activeHint: 'Turn off to remove access immediately',
    viewAll: 'Sees all bookings',
    viewAllHint: 'Otherwise only bookings for their linked resources',
    linked: (label: string) => `Linked ${label.toLowerCase()}s`,
    save: 'Save',
    noLinks: 'Not linked to anything yet',
  },
  invite: {
    loading: 'Opening invitation…',
    title: (business: string) => `Join ${business}`,
    body: (email: string) => `You've been invited as staff with ${email}.`,
    linked: (name: string) => `Your schedule: ${name}`,
    newAccount: 'Create your staff login',
    name: 'Your name',
    phone: 'Mobile number',
    password: 'Choose a password',
    existing: 'You already have an OutletBooking login. Enter your password to join.',
    password2: 'Password',
    join: 'Join',
    wrongAccount: (email: string) => `You're logged in as ${email}. Log out to accept this invitation.`,
    joinAs: (email: string) => `Join as ${email}`,
    expired: 'This invitation has expired. Ask the owner to send a new one.',
    accepted: 'This invitation has already been used. Log in with your email.',
    notFound: 'This invitation link is not valid. Ask the owner to send a new one.',
    goToLogin: 'Go to log in',
  },
  placeholder: {
    calendar: 'Day and week calendar by resource arrives in Phase 3.',
    bookings: 'Search and filter bookings arrives in Phase 3.',
    setup: 'Services, resources and working hours arrive in Phase 2.',
    reports: 'Revenue, no-shows and utilisation arrive in Phase 6.',
    staffToday: "Your bookings for today will appear here.",
    schedule: 'Your upcoming schedule will appear here.',
  },
} as const;

export const t = en;
