/** All UI copy in one place (Bahasa Malaysia added later as strings/ms.ts with the same shape). */
export const en = {
  appName: 'OutletBooking',
  tagline: 'Bookings, payments and your team in one app.',
  common: {
    retry: 'Try again',
    loading: 'Loading…',
    genericError: 'Something went wrong. Please try again.',
    networkError: "Can't reach the server. Check your connection and that the API is running.",
    comingSoon: 'Coming soon',
    logout: 'Log out',
    continue: 'Continue',
    back: 'Back',
    required: 'required',
  },
  login: {
    title: 'Welcome back',
    email: 'Email',
    password: 'Password',
    keepLoggedIn: 'Keep me logged in',
    forgot: 'Forgot password?',
    submit: 'Log in',
    staffNote: "Staff: log in with the email your business owner invited. You'll see your own schedule.",
    newHere: 'New to OutletBooking?',
    startTrial: 'Start 7-day free trial',
    invalid: 'Wrong email or password.',
  },
  signup: {
    step: (n: number) => `Step ${n} of 3`,
    accountTitle: 'Create your account',
    name: 'Your name',
    email: 'Email',
    phone: 'Mobile number',
    phoneHint: 'e.g. 012-345 6789',
    password: 'Password',
    passwordHint: 'At least 8 characters',
    businessTitle: 'Set up your business',
    businessName: 'Business name',
    bookingLink: 'Your booking link',
    available: 'Available',
    taken: 'Already taken',
    invalidSlug: '3–50 letters, numbers or dashes',
    checking: 'Checking…',
    kind: 'What kind of business?',
    trialNote: '7-day free trial · no card needed',
    // O1c · step 3, one screen for every business type
    setupTitle: {
      sports: 'Add your courts & hours',
      real_estate: 'Add your agents & viewing hours',
      vehicle_inspection: 'Add your bays & services',
      barber_salon: 'Add your stylists & services',
      workshop: 'Add your bays & jobs',
      clinic: 'Add your practitioners & hours',
      tuition: 'Add your teachers & classes',
      other: 'Set up what customers book',
    },
    setupBody: (type: string) => `Filled in from the ${type} template. You can change all of this later in Setup.`,
    whatBook: 'What do customers book?',
    howMany: (label: string) => `How many ${label.toLowerCase()}s?`,
    fewer: 'Fewer',
    more: 'More',
    yourPeople: (label: string) => `Your ${label.toLowerCase()}s`,
    addPerson: (label: string) => `+ Add ${label.toLowerCase()}`,
    you: (label: string) => `You · Owner & ${label.toLowerCase()}`,
    inviteLater: 'Invite later in Setup → Staff',
    personName: (n: number) => `Name ${n}`,
    remove: 'Remove',
    customersPick: (label: string) => `Customers pick a ${label.toLowerCase()}`,
    customersPickHint: (label: string) => `Or “Any ${label.toLowerCase()}” for the earliest slot`,
    travelTitle: 'Travel time between viewings',
    travelHint: 'Viewings happen at the property address. We keep this gap free so agents can drive between units.',
    none: 'None',
    mobileTitle: 'Mobile inspection',
    mobileHint: 'Inspector goes to the customer or seller',
    mobileFee: 'Fee',
    mobileArea: 'Area',
    askedFor: 'Customers will be asked for',
    askedForHint: 'Change these later in Setup → Booking form.',
    pricesFromNote: 'Prices shown as “from” — final bill can change after diagnosis.',
    firstService: 'Your first service',
    serviceName: 'Service name',
    length: 'Length',
    openingHours: 'Opening hours',
    edit: 'Edit',
    done: 'Done',
    closed: 'Closed',
    open: 'Open',
    from: 'From',
    to: 'To',
    confirmQuestion: 'To confirm a booking, customers',
    servicesHeading: 'What can customers book?',
    nameRequired: 'Enter a name for each one',
    firstServiceRequired: 'Enter your first service',
    servicesTitle: 'Review your services',
    servicesBody: 'We added sample services for your type of business. Set your prices — you can change everything later in Setup.',
    servicesEmpty: 'No sample services for this business type. Add your own in Setup → Services.',
    durationLabel: 'Duration',
    durationsFixed: (list: string) => `Customers choose ${list}`,
    priceLabel: 'Price',
    pricePerBlock: (d: string) => `Price per ${d}`,
    nextUp: 'Next: add your courts, staff or rooms and their working hours in Setup.',
    finish: 'Finish',
    skip: 'Skip for now',
    priceInvalid: 'Enter a valid amount',
    haveAccount: 'Already have an account?',
    login: 'Log in',
  },
  templates: {
    real_estate: { title: 'Real estate viewing', sub: 'Book by agent' },
    vehicle_inspection: { title: 'Vehicle inspection', sub: 'Book by bay' },
    sports: { title: 'Sports courts', sub: 'Book by court' },
    workshop: { title: 'Workshop', sub: 'Book by bay' },
    barber_salon: { title: 'Barber / Salon', sub: 'Book by stylist' },
    other: { title: 'Other', sub: 'Clinic, tuition, more' },
    clinic: { title: 'Clinic', sub: 'Book by practitioner' },
    tuition: { title: 'Tuition', sub: 'Book by teacher' },
  },
  forgot: {
    screen: 'Forgot password',
    title: 'Reset your password',
    body: "Enter the email you log in with. We'll send a link to set a new password.",
    email: 'Email',
    submit: 'Send reset link',
    sentTitle: 'Check your email.',
    sentBody: (email: string) => `If ${email} has an account, we sent a link to set a new password.`,
    sentHint: "The link works for 30 minutes. Didn't get it? Check spam or",
    sendAgain: 'send again',
    sentAgain: 'Sent again.',
    backToLogin: 'Back to log in',
  },
  reset: {
    screen: 'Set new password',
    title: 'Choose a new password',
    forEmail: (email: string) => `For ${email}`,
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    minLength: 'At least 8 characters',
    match: 'Passwords match',
    logoutOthers: 'Log out other devices',
    logoutOthersHint: 'Recommended if you think someone else knows it',
    submit: 'Save & log in',
    invalidTitle: 'This link has expired',
    invalidBody: 'Reset links work once, for 30 minutes. Ask for a new one.',
    newLink: 'Send a new link',
  },
  today: {
    notifications: (n: number) => (n ? `Notifications, ${n} unread` : 'Notifications'),
    trial: (days: number) => `Free trial · ${days} ${days === 1 ? 'day' : 'days'} left`,
    trialEnded: 'Free trial ended',
    choosePlan: 'Choose a plan',
    bookingsToday: 'Bookings today',
    expectedRevenue: 'Expected revenue',
    checkedIn: 'Checked in',
    noShow: 'No-show',
    newBooking: 'New booking',
    walkIn: 'Walk-in',
    shareLink: 'Share link',
    upNext: 'Up next',
    seeCalendar: 'See calendar',
    nothingNext: 'Nothing else today',
    nothingNextBody: 'All of today’s bookings are done. Tap New booking or Walk-in to add one.',
    awaitingPayment: 'Awaiting payment',
    hours: (min: number) => (min % 60 === 0 ? `${min / 60} hr` : `${min} min`),
    emptyTitle: 'No bookings yet',
    emptyBody: 'Share your booking link so customers can book you 24/7.',
    shareMessage: (name: string, url: string) => `Book ${name} online: ${url}`,
    checklist: {
      title: 'Get ready for your first booking',
      progress: (done: number, total: number) => `${done} of ${total}`,
      hide: 'Hide',
      done: 'Done',
      account: 'Create your account',
      resources: (label: string) => `Add ${label.toLowerCase()}s & hours`,
      resourcesSub: (n: number, label: string) =>
        n === 0 ? 'So customers can see free times' : `${n} ${label.toLowerCase()}${n === 1 ? '' : 's'} with working hours`,
      payments: 'Connect ToyyibPay',
      paymentsSub: 'So customer payments reach your bank',
      shareLink: 'Share your booking link',
      shareLinkSub: 'WhatsApp, Instagram, QR at the counter',
      testBooking: 'Make a test booking',
      testBookingSub: 'See what your customers see',
      hideTitle: 'Hide the checklist?',
      hideBody: 'You can still do every step from Setup.',
    },
  },
  notifications: {
    title: 'Notifications',
    markAllRead: 'Mark all read',
    today: 'Today',
    yesterday: 'Yesterday',
    earlier: 'Earlier',
    empty: 'No notifications yet',
    emptyBody: 'New bookings, cancellations and team updates show here.',
    unread: 'Unread',
  },
  offline: {
    banner: (time: string | null) => (time ? `You're offline · showing data from ${time}` : "You're offline"),
    readOnly: 'While offline you can view bookings. Changes are turned off until you are back online.',
    retry: 'Retry',
  },
  toast: {
    undo: 'Undo',
  },
  payments: {
    title: 'Payments',
    subtitle: 'How customers pay you',
    connected: 'ToyyibPay connected',
    notConnected: 'Not connected',
    keyEnding: (last4: string) => `Key ending …${last4}`,
    testPassed: (when: string) => `Test payment of RM 1.00 passed · ${when}`,
    testNeeded: 'Run the RM 1.00 test payment to make sure money reaches you.',
    testWaiting: 'Waiting for your RM 1.00 test payment.',
    moneyFlow: 'Customer payments go straight to your ToyyibPay account, then to your bank. OutletBooking never holds your money.',
    steps: 'Set up in 3 steps',
    step1: 'Have a ToyyibPay account',
    step1Sub: 'Free to open. Needs your SSM and bank details.',
    openToyyibPay: 'Open toyyibpay.com',
    step2: 'Paste your User Secret Key',
    step2Help: 'Where do I find this? In ToyyibPay: Dashboard → Settings → User Secret Key.',
    keyLabel: 'User Secret Key',
    keyHint: 'e.g. abcd1234-ef56-…',
    step3: 'We create your payment category',
    step3Sub: (name: string) => `“OutletBooking ${name}” — done automatically`,
    connect: 'Connect ToyyibPay',
    runTest: 'Run RM 1.00 test payment',
    checkTest: 'Check test payment',
    testNotYet: 'ToyyibPay has not confirmed the test payment yet. Finish it in the browser, then check again.',
    rule: 'Payment to confirm a booking',
    ruleLink: 'Change payment rule',
    fees: 'ToyyibPay charges its own fee for each payment. Your key is stored encrypted and is never shown to staff.',
    disconnect: 'Disconnect ToyyibPay',
    disconnectTitle: 'Disconnect ToyyibPay?',
    disconnectBody: 'Customers will not be able to pay online until you connect again. Payments already made are kept.',
    rowConnected: 'ToyyibPay connected',
    rowTestPending: 'Connected · run the RM 1 test',
    rowNotConnected: 'Connect ToyyibPay to take deposits online',
    sandbox: 'Test mode (sandbox) — use your dev.toyyibpay.com account',
  },
  reminders: {
    title: "Remind tomorrow's customers",
    count: (n: number) => `${n} booking${n === 1 ? '' : 's'}`,
    message: 'Message',
    edit: 'Edit',
    done: 'Done',
    template: 'Hi {name}, a reminder of your {service} booking at {business} tomorrow, {time} on {resource}. Can’t make it? Reply to this message.',
    placeholders: 'Use {name}, {service}, {business}, {time}, {resource}',
    progress: (sent: number, total: number) => `${sent} of ${total} sent`,
    send: 'Send',
    sent: 'Sent ✓',
    sendNext: (name: string) => `Send next · ${name}`,
    allSent: 'All reminders sent',
    hint: 'Each tap opens WhatsApp with the message ready. Automatic reminders come later.',
    empty: 'No bookings tomorrow',
    emptyBody: 'Nothing to remind. Bookings for tomorrow show here.',
    noPhone: 'No phone number',
    open: "Remind tomorrow's customers",
  },
  tabs: {
    today: 'Today',
    calendar: 'Calendar',
    bookings: 'Bookings',
    setup: 'Setup',
    reports: 'Reports',
    schedule: 'Schedule',
    profile: 'Profile',
  },
  account: {
    title: 'My account',
    role: { owner: 'Owner', staff: 'Staff' },
    roleAt: (role: string, business: string) => `${role} · ${business}`,
    email: 'Email',
    mobile: 'Mobile',
    noMobile: 'Not added',
    changePassword: 'Change password',
    app: 'App',
    language: 'Language',
    english: 'English',
    logout: 'Log out',
    open: 'Open my account',
    help: 'Help on WhatsApp',
    helpHint: 'We usually reply within the hour',
    helpMessage: (business: string) => `Hi FTech, I need help with OutletBooking (${business}).`,
    deleteAccount: 'Delete my account and business data',
  },
  deleteAccount: {
    title: 'Delete account',
    heading: 'This cannot be undone',
    body: (business: string) =>
      `Your login and ${business} will be permanently deleted, including all bookings, customers, services, payments records and staff access. Staff logins used only for this business are deleted too. Your booking page stops working.`,
    password: 'Your password',
    confirmName: 'Type your business name to confirm',
    confirmNameHint: (business: string) => `Type: ${business}`,
    submit: 'Delete everything',
    confirmTitle: 'Delete permanently?',
    confirmBody: 'All data for this business will be erased now.',
    confirmButton: 'Delete',
    wrongPassword: 'Your password is not correct.',
    wrongName: 'Type your business name exactly as shown.',
  },
  changePassword: {
    title: 'Change password',
    current: 'Current password',
    newPassword: 'New password',
    confirmPassword: 'Confirm new password',
    minLength: 'At least 8 characters',
    logoutOthers: 'Log out other devices',
    logoutOthersHint: 'This phone stays logged in',
    submit: 'Save new password',
    wrongCurrent: 'Your current password is not right.',
  },
  setup: {
    title: 'Setup',
    yourBusiness: 'Your business',
    account: 'Account',
    save: 'Save',
    saved: 'Saved',
    add: 'Add',
    cancel: 'Cancel',
    delete: 'Delete',
    archive: 'Archive',
    hidden: 'Hidden',
    inactive: 'Inactive',
    all: 'All',
    menu: {
      profile: 'Business profile',
      profileSub: 'Name, logo, address, WhatsApp number',
      services: 'Services & pricing',
      servicesSub: (n: number) => (n === 1 ? '1 service' : `${n} services`),
      resources: (label: string) => `${label}s & working hours`,
      resourcesSub: (n: number) => (n === 0 ? 'None yet — add one to take bookings' : `${n} set up`),
      timeOff: 'Time off & closures',
      timeOffSub: 'Public holidays, leave, maintenance',
      fields: 'Booking form questions',
      fieldsSub: (n: number) => (n === 1 ? '1 extra question' : `${n} extra questions`),
      staff: 'Staff',
      staffSub: 'Invite your team and link them to their schedule',
      bookingOff: 'Online booking is paused',
      // ST · template-driven Setup tab
      bookingPage: 'Your booking page',
      share: 'Share',
      shareMessage: (business: string, link: string) => `Book ${business} online: ${link}`,
      whatCustomersBook: 'What customers book',
      rulesSection: 'Rules',
      businessSection: 'Business',
      onlyThisType: 'Only for this type',
      soon: 'Soon',
      resourcesTitle: (label: string) => `${label}s`,
      resourcesCount: (n: number, label: string) => (n === 0 ? `None yet — add your first ${label.toLowerCase()}` : `${n} ${label.toLowerCase()}${n === 1 ? '' : 's'}`),
      linkedStaff: (n: number) => `${n} linked to staff`,
      servicesTitle: {
        sports: 'Sports & prices',
        real_estate: 'Viewing types',
        vehicle_inspection: 'Inspection services',
        workshop: 'Jobs & prices',
        barber_salon: 'Services & prices',
        clinic: 'Services & prices',
        tuition: 'Classes & prices',
        other: 'Services & prices',
      },
      servicesCount: (n: number) => (n === 0 ? 'None yet — add one' : n === 1 ? '1 service' : `${n} services`),
      free: 'free',
      openingHours: 'Opening hours',
      hoursVary: (label: string) => `Different for each ${label.toLowerCase()}`,
      hoursNone: 'Not set yet',
      rulesLine: (ahead: string, days: number, cancel: string | null) =>
        [`Book ${ahead} ahead`, `up to ${days} days`, cancel ? `cancel ${cancel} before` : 'no online cancelling'].join(' · '),
      noLimit: 'any time',
      paymentRow: 'Payment to confirm',
      paymentSummary: {
        full: 'Pay in full online',
        deposit: (deposit: string, place: string) => `Deposit ${deposit} · balance at ${place}`,
        at_venue: (place: string) => `Pay at ${place}`,
        none: 'No payment',
        mixed: 'Different for each service',
        empty: 'Add a service first',
      },
      bookingForm: 'Booking form',
      bookingFormLine: (extra: string[]) => ['Name, mobile', ...extra].join(', '),
      staffRoles: 'Staff & roles',
      staffCount: (n: number) => (n === 0 ? 'Just you · invite your team' : `${n} staff`),
      reminders: 'Reminders & WhatsApp',
      remindersSub: "Remind tomorrow's customers on WhatsApp",
      paymentsRow: 'Payments (ToyyibPay)',
      plan: 'Plan & billing',
      planTrial: (days: number) => (days > 0 ? `Free trial · ${days} day${days === 1 ? '' : 's'} left` : 'Free trial ended'),
      planActive: (plan: string) => `${plan[0]?.toUpperCase()}${plan.slice(1)} plan`,
      extras: {
        peak_hours: { title: 'Peak hours', on: (n: number) => `Peak prices on ${n} service${n === 1 ? '' : 's'}`, off: 'Off · charge more at busy times' },
        booking_length: { title: 'Booking length', fixed: 'Fixed length per service', changeover: (m: string) => `${m} changeover` },
        listings: { title: 'Listings' },
        travel: { title: 'Travel time & areas', between: (m: string) => `${m} between viewings`, none: 'No travel time', areas: 'Add areas' },
        mobile_inspection: { title: 'Mobile inspection', on: 'On', off: 'Off', fee: (fee: string) => `${fee} fee` },
        checklist: { title: 'Checklist & report' },
        resource_schedules: { title: (label: string) => `${label} schedules`, sub: (label: string) => `Each ${label.toLowerCase()} sets own hours and days off` },
        walk_in_queue: { title: 'Walk-in queue' },
        quotes: { title: 'Quotes before work' },
        pickup_dropoff: { title: 'Pick-up & drop-off' },
        resource_label: { title: 'What you call it', sub: (label: string) => `“${label}” · rename to Doctor, Teacher, Coach…` },
        group_bookings: { title: 'Group bookings' },
      },
    },
    /** Where customers pay when they pay "at the visit", per business type. */
    place: {
      sports: 'venue',
      real_estate: 'viewing',
      vehicle_inspection: 'centre',
      workshop: 'workshop',
      barber_salon: 'shop',
      clinic: 'clinic',
      tuition: 'centre',
      other: 'venue',
    },
    setupExtra: {
      save: 'Save',
      none: 'None',
      unknown: 'This setting does not exist.',
      noService: 'No home or property visits',
      noServiceBody: 'Add a service with location “At the customer’s address” first.',
      travel: {
        title: 'Travel time & areas',
        intro: 'Viewings happen at the property address. We keep this gap free so agents can drive between units.',
        gap: 'Travel time between viewings',
        gapHint: 'Applies to viewings at the property.',
        area: 'Areas you cover',
        areaHint: 'e.g. Puchong, Kinrara, Subang',
      },
      mobile: {
        title: 'Mobile inspection',
        intro: 'Inspector goes to the customer or seller.',
        offer: 'Offer mobile inspection',
        offerHint: 'Off = hidden from your booking page',
        fee: 'Travel fee',
        feeHint: 'Shown to customers on your booking page',
        area: 'Area',
        areaHint: 'e.g. Klang Valley',
      },
    },
    paymentRule: {
      title: 'Payment to confirm',
      intro: 'Applies to every service. You can still change a single service in Services.',
      question: 'To confirm a booking, customers',
      full: 'Pay in full',
      deposit: 'Pay deposit',
      fee: 'Booking fee',
      none: 'No payment',
      at_venue: (place: string) => `Pay at ${place}`,
      hint: {
        full: 'They pay the whole price online when booking.',
        deposit: 'They pay a deposit online; the rest at the visit. Services without a deposit get the default amount.',
        fee: 'They pay a small fee online to confirm the viewing.',
        none: 'Nothing to pay. You confirm the booking.',
        at_venue: 'Nothing online. They pay when they come.',
      },
      mixedNote: 'Your services use different rules now. Choosing one changes all of them.',
      save: 'Apply to all services',
    },
    profile: {
      title: 'Business profile',
      rulesTitle: 'Booking rules',
      rulesSub: 'Applies to your booking page',
      details: 'Details',
      bookingLink: 'Booking link',
      bookingLinkHint: 'Changing this breaks QR posters you already printed.',
      slugTaken: 'This link is already taken. Try another.',
      businessType: 'Business type',
      businessTypeHint: 'Contact us to change',
      saveProfile: 'Save changes',
      saveRules: 'Save rules',
      whenCanBook: 'When customers can book',
      slotIntervalHint: 'e.g. 8:00, 8:30, 9:00',
      minAdvanceShort: 'Book at least',
      minAdvanceShortHint: 'No last-minute surprises',
      ahead: (label: string) => `${label} ahead`,
      maxDaysHint: 'How far ahead the calendar opens',
      days: (n: number) => `${n} days`,
      cancelUntil: 'Until',
      lateDeposit: 'Deposit if they cancel late',
      kept: 'Kept',
      refunded: 'Refunded',
      noCancelOnline: 'Customers see: “To cancel, please contact us.”',
      customersSee: (cutoff: string, kept: boolean) =>
        `Customers see: “Free cancellation until ${cutoff}.${kept ? ' Late cancellations keep the deposit.' : ''}”`,
      anytime: 'the start time',
      name: 'Business name',
      phone: 'Phone',
      whatsapp: 'WhatsApp number',
      whatsappHint: 'Customers tap this to message you',
      email: 'Email',
      address: 'Address',
      description: 'About your business',
      descriptionHint: 'Shown on your booking page',
      resourceLabel: 'What do customers book?',
      resourceLabelHint: 'e.g. Court, Bay, Agent, Room',
      rules: 'Booking rules',
      slotInterval: 'Start times every',
      minAdvance: 'Earliest booking',
      minAdvanceHint: 'How soon before the start a customer can book',
      maxDaysAhead: 'Book up to (days ahead)',
      payment: 'Payment',
      holdUnpaid: 'Hold unpaid bookings for',
      holdUnpaidHint: 'Slot is released if not paid in time',
      autoConfirmPaid: 'Confirm automatically when paid',
      autoConfirmPaidHint: 'Off = you approve each booking',
      cancelling: 'Cancelling',
      customersCanCancel: 'Customers can cancel online',
      customersCanCancelHint: 'From the link in their confirmation',
      cancelCutoff: 'Customers can cancel up to',
      cancelCutoffHint: 'After this, they must contact you',
      lateCancelKeepsDeposit: 'Keep the deposit if they cancel late',
      lateCancelKeepsDepositHint: 'Shown to customers before they pay',
      bookingEnabled: 'Accept online bookings',
      bookingEnabledHint: 'Turn off to pause your booking page',
      none: 'No limit',
      before: (label: string) => `${label} before`,
    },
    services: {
      title: 'Services & pricing',
      newTitle: 'New service',
      editTitle: 'Edit service',
      empty: 'No services yet',
      emptyBody: 'Add what customers can book, with duration and price.',
      add: 'Add service',
      name: 'Service name',
      description: 'Description',
      block: 'Duration',
      blockHint: 'Length of one booking (or one block when customers choose)',
      customMin: 'Minutes',
      choose: 'Customer can choose',
      chooseHint: 'Leave all off for a fixed duration',
      priceUnit: 'Price',
      perBooking: 'Per booking',
      perBlock: 'Per block',
      price: 'Price',
      pricePerBlock: (d: string) => `Price per ${d}`,
      peak: 'Peak pricing',
      addRule: '+ Add rule',
      noRules: 'Same price all week',
      ruleTitle: 'Peak price rule',
      ruleName: 'Name',
      ruleDays: 'Days',
      ruleFrom: 'From',
      ruleTo: 'To',
      rulePrice: 'Peak price',
      ruleSave: 'Add rule',
      ruleDaysError: 'Pick at least one day',
      ruleTimeError: 'End must be after start',
      payment: 'Payment to confirm',
      payFull: 'Full payment upfront',
      payDeposit: 'Deposit only',
      payDepositHint: '· set amount',
      payVenue: 'Pay at venue',
      deposit: 'Deposit amount',
      location: 'Where does it happen?',
      atBusiness: 'At my business',
      atCustomer: "At the customer's location",
      atCustomerHint: 'Customer enters an address (viewings, mobile inspection)',
      buffer: 'Buffer after (min)',
      bufferHint: 'Clean-up or rest time after each booking',
      travelBuffer: 'Travel time (min)',
      travelBufferHint: 'Blocked before and after for travel',
      visible: 'Show on booking page',
      resources: (label: string) => `${label}s that offer this`,
      noResources: (label: string) => `Add a ${label.toLowerCase()} first, then assign it here.`,
      save: 'Save service',
      archiveTitle: 'Archive this service?',
      archiveBody: 'It will be removed from your booking page. Past bookings are kept.',
      perBlockShort: '/block',
    },
    resources: {
      title: (label: string) => `${label}s & working hours`,
      labelNote: 'Label set by your template · rename in Business profile',
      newTitle: (label: string) => `New ${label.toLowerCase()}`,
      empty: (label: string) => `No ${label.toLowerCase()}s yet`,
      emptyBody: 'Add what customers book, then set its working hours.',
      add: (label: string) => `Add ${label.toLowerCase()}`,
      name: 'Name',
      type: 'Type',
      types: { staff: 'Staff', bay: 'Bay', court: 'Court', room: 'Room', property: 'Property', other: 'Other' },
      active: 'Taking bookings',
      services: 'Services offered',
      linkedStaff: 'Linked staff login',
      noLinkedStaff: 'Not linked',
      hours: 'Working hours',
      closed: 'Closed',
      addBreak: '+ Add hours',
      copyHours: (label: string) => `Copy these hours to other ${label.toLowerCase()}s`,
      copyTitle: 'Copy working hours',
      copyBody: (label: string) => `Replaces the working hours of the selected ${label.toLowerCase()}s.`,
      copyDone: 'Hours copied',
      saveHours: 'Save hours',
      hoursSaved: 'Working hours saved',
      save: 'Save',
      createFirst: 'Save first, then set working hours.',
      archiveTitle: (label: string) => `Archive this ${label.toLowerCase()}?`,
      archiveBody: 'It stops taking bookings and frees a slot on your plan. Past bookings are kept.',
      timeOff: 'Time off & closures',
      noHours: 'No working hours set',
      limitReached: 'You have reached your plan limit.',
    },
    timeOff: {
      title: 'Time off & closures',
      empty: 'No upcoming time off',
      emptyBody: 'Add public holidays, leave or maintenance so nobody can book then.',
      add: '+ Add',
      newTitle: 'Add time off',
      appliesTo: 'Applies to',
      wholeBusiness: 'Whole business',
      from: 'From',
      to: 'To',
      allDay: 'All day',
      startTime: 'Start time',
      endTime: 'End time',
      reason: 'Reason (optional)',
      reasonHint: 'e.g. Hari Raya, resurfacing, annual leave',
      save: 'Add time off',
      deleteTitle: 'Delete this time off?',
      deleteBody: 'Customers will be able to book this time again.',
      rangeError: 'End must be after start',
      allLabel: 'All',
    },
    fields: {
      title: 'Booking form questions',
      intro: 'Customers answer these when booking. Name and phone are always asked.',
      empty: 'No extra questions',
      emptyBody: 'Add questions like plate number or number of players.',
      add: '+ Add',
      newTitle: 'New question',
      editTitle: 'Edit question',
      label: 'Question',
      key: 'Field key',
      keyHint: 'Used in reports and search. Changing it hides old answers from search.',
      type: 'Answer type',
      types: { text: 'Text', number: 'Number', select: 'Dropdown', date: 'Date', address: 'Address', phone: 'Phone' },
      options: 'Dropdown options',
      addOption: '+ Add option',
      optionPlaceholder: (n: number) => `Option ${n}`,
      required: 'Required',
      searchable: 'Searchable',
      searchableHint: 'Find bookings by this answer (e.g. plate number)',
      hint: 'Example answer (optional)',
      hintHint: 'Shown greyed out in the empty box',
      showToStaff: 'Show answer to staff',
      showToStaffHint: 'Off = only you and staff who can change setup see it',
      active: 'Show on booking form',
      appliesTo: 'Ask for',
      allServices: 'All services',
      save: 'Save question',
      deleteTitle: 'Delete this question?',
      deleteBody: 'Answers already given stay on past bookings.',
      moveUp: 'Move up',
      moveDown: 'Move down',
      requiredTag: 'Required',
    },
  },
  staff: {
    title: 'Staff',
    team: 'Your team',
    pending: 'Invitations waiting',
    invite: 'Invite staff',
    inviteTitle: 'Invite a staff member',
    inviteBody: "They get a link to create their login. You'll share it by WhatsApp, email or SMS.",
    email: 'Their email',
    linkTo: (label: string) => `Their ${label.toLowerCase()} (optional)`,
    linkHint: 'Staff only see bookings for what is linked to them',
    none: 'None',
    send: 'Create invite link',
    shareMessage: (business: string, url: string) =>
      `You're invited to join ${business} on OutletBooking. Tap to set up your staff login: ${url}`,
    share: 'Share link',
    revokeTitle: 'Cancel this invitation?',
    revokeBody: 'The link will stop working.',
    revoke: 'Cancel invite',
    expires: (date: string) => `Link valid until ${date}`,
    owner: 'Owner',
    staffRole: 'Staff',
    inactive: 'No access',
    empty: 'Just you so far',
    emptyBody: 'Invite staff so they can see their own schedule and check customers in.',
    memberTitle: 'Staff access',
    active: 'Can log in',
    activeHint: 'Turn off to remove access immediately',
    viewAll: 'Can see all bookings',
    viewAllHint: 'Off = only their own',
    takePayments: 'Can take payments',
    takePaymentsHint: 'Record cash, DuitNow and card',
    editSetup: 'Can change setup',
    editSetupHint: 'Services, prices and hours',
    permissions: 'What they can do',
    ownerSummary: 'Sees everything',
    perm: { all: 'all bookings', own: 'own bookings', pay: 'takes payments', setup: 'changes setup' },
    linked: (label: string) => `Linked ${label.toLowerCase()}s`,
    save: 'Save',
    noLinks: 'Not linked to anything yet',
  },
  invite: {
    loading: 'Opening invitation…',
    title: (business: string) => `Join ${business}`,
    body: (email: string) => `You've been invited as staff with ${email}.`,
    linked: (name: string) => `Your schedule: ${name}`,
    newAccount: 'Create your staff login',
    name: 'Your name',
    phone: 'Mobile number',
    password: 'Choose a password',
    existing: 'You already have an OutletBooking login. Enter your password to join.',
    password2: 'Password',
    join: 'Join',
    wrongAccount: (email: string) => `You're logged in as ${email}. Log out to accept this invitation.`,
    joinAs: (email: string) => `Join as ${email}`,
    expired: 'This invitation has expired. Ask the owner to send a new one.',
    accepted: 'This invitation has already been used. Log in with your email.',
    notFound: 'This invitation link is not valid. Ask the owner to send a new one.',
    goToLogin: 'Go to log in',
  },
  book: {
    loading: 'Opening booking page…',
    notFound: 'This booking link is not valid. Check the link with the business.',
    pageTitle: (name: string) => `Book ${name}`,
    services: 'Services',
    noServices: 'No services are listed yet.',
    free: 'Free',
    deposit: (amount: string) => `${amount} deposit`,
    atYourPlace: 'At your location',
    paused: 'Online booking is paused. Contact the business to book.',
    whatsapp: 'WhatsApp us',
    call: 'Call',
    poweredBy: 'Powered by OutletBooking',
    step: (n: number, total: number) => `Step ${n} of ${total}`,
    // Step 1
    chooseService: 'Choose a service',
    whatToBook: 'What would you like to book?',
    fullPayment: 'Full payment to confirm',
    // Step 2
    pickTime: 'Pick a time',
    howLong: 'How long?',
    any: 'Any available',
    anyHint: 'Earliest free',
    date: 'Date',
    noSlots: 'No free times on this day. Try another day.',
    slotsError: "Couldn't load times.",
    // C2 court grid (sports)
    booked: 'Booked',
    gridHint: (hours: string) => `Tap a start time; ${hours} are held for you.`,
    // F2 fully booked
    fullyBooked: (date: string) => `Fully booked on ${date}`,
    fullyBookedBody: (label: string, duration: string, canShorten: boolean) =>
      `All ${label.toLowerCase()}s are taken for ${duration}. ${canShorten ? 'Try a shorter time, or another day.' : 'Try another day.'}`,
    nextAvailable: 'Next available',
    nothingSoon: 'No free times in the next few weeks.',
    askCancellations: (name: string) => `Ask ${name} about cancellations`,
    // Step 3
    yourDetails: 'Your details',
    fullName: 'Full name',
    mobile: 'Mobile number',
    mobileHint: 'The business uses this number to contact you about the booking.',
    address: 'Address',
    addressHint: 'Where should we come?',
    notes: 'Notes',
    optional: '(optional)',
    total: 'Total',
    payNow: (mode: 'deposit' | 'full') => (mode === 'deposit' ? 'Deposit to confirm' : 'Pay to confirm'),
    payLater: 'Pay at the venue',
    balanceLater: (amount: string) => `Balance ${amount} paid later`,
    payNote: 'Online payment (FPX / DuitNow) is coming soon. Your slot is held for a short time; the business will contact you about payment.',
    payOnlineNote: 'You pay by FPX online banking right after booking. Your slot is held for you while you pay.',
    payTitle: 'Pay to confirm',
    payFailedTitle: 'Payment not completed',
    payFailedBody: "Your bank didn't confirm the payment. You have not been booked yet.",
    heldFor: 'held for you',
    timeLeft: (mmss: string) => `${mmss} left`,
    payAmount: (amount: string) => `Pay ${amount}`,
    tryAgain: (amount: string) => `Try again · ${amount}`,
    checkingPayment: 'Checking your payment…',
    openingPayment: 'Opening ToyyibPay…',
    payFailedHelp: (ref: string) => `If the timer runs out, the slot is released and you won't be booked. If money left your account, contact your bank with reference ${ref}, or`,
    whatsappShort: (name: string) => `WhatsApp ${name}`,
    pickDifferentTime: 'Pick a different time',
    holdEnded: 'The time held for you ran out, so this booking was released. Please book again.',
    payByBusiness: 'The business will contact you about payment.',
    cancelPolicy: (time: string) => `Free cancellation up to ${time} before start.`,
    bookNow: 'Book now',
    slotTaken: 'Sorry, that time was just taken. Please pick another time.',
    // Confirmation (C4)
    titles: {
      confirmed: "You're booked!",
      pending: 'Booking received',
      cancelled: 'Booking cancelled',
      completed: 'Thanks for visiting',
      checked_in: "You're checked in",
      no_show: 'Booking missed',
    },
    pendingBody: (amount: string, until: string) => `Pay ${amount} to confirm. Your slot is held until ${until}.`,
    saveLink: 'Bookmark this page to view or cancel your booking later.',
    ref: 'Booking ref',
    where: 'Where',
    when: 'When',
    address2: 'Address',
    price: 'Price',
    toPay: 'To pay',
    paid: 'Paid',
    name: 'Name',
    addToCalendar: 'Add to calendar',
    googleCalendar: 'Google Calendar',
    whatsappBusiness: (name: string) => `WhatsApp ${name}`,
    whatsappMessage: (ref: string, when: string) => `Hi, about my booking ${ref} on ${when}.`,
    directions: 'Get directions',
    cancel: 'Cancel this booking',
    cancelUntil: (when: string) => `Free cancellation until ${when}`,
    cancelTitle: 'Cancel this booking?',
    cancelBody: 'The time will be released for other customers.',
    cancelConfirm: 'Yes, cancel',
    contactToChange: 'To change or cancel, contact the business.',
    bookAgain: 'Make another booking',
    bookingNotFound: 'This booking link is not valid. Check the link the business sent you.',
    // QR poster
    scanToBook: 'Scan to book',
    posterBody: 'Book online 24/7 — no app needed.',
    print: 'Print or save as PDF',
  },
  share: {
    title: 'Share your booking link',
    copy: 'Copy link',
    copied: 'Link copied',
    whatsapp: 'Share on WhatsApp',
    poster: 'QR poster',
    more: 'More apps',
    qrLabel: (name: string) => `QR code for ${name}'s booking link`,
    tip: 'Tip: add this link to your WhatsApp Business profile, Instagram bio and Google Business listing. Print the QR poster for your counter.',
    bookingOff: 'Online booking is switched off. Turn it on in Setup → Business profile so customers can book.',
  },
  calendar: {
    title: 'Calendar',
    day: 'Day',
    week: 'Week',
    prevDay: 'Previous day',
    nextDay: 'Next day',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    today: 'Today',
    summary: (bookings: number, resources: number, label: string) =>
      `${bookings} booking${bookings === 1 ? '' : 's'} · ${resources} ${label.toLowerCase()}${resources === 1 ? '' : 's'}`,
    weekSummary: (bookings: number) => `${bookings} booking${bookings === 1 ? '' : 's'} this week`,
    noResources: 'Nothing to show yet',
    noResourcesBody: 'Add your courts, staff or rooms in Setup first.',
    noBookingsDay: 'No bookings this day',
    newBooking: 'New booking',
    walkIn: 'Walk-in',
  },
  bookingsList: {
    title: 'Bookings',
    search: 'Search name, phone or plate',
    clear: 'Clear search',
    filters: { all: 'All', upcoming: 'Upcoming', unpaid: 'Unpaid', past: 'Past' },
    upcoming: 'Upcoming',
    past: 'Past',
    count: (n: number) => `${n} booking${n === 1 ? '' : 's'}`,
    matching: (n: number, customers: number, q: string) =>
      `${n} booking${n === 1 ? '' : 's'} for ${customers} customer${customers === 1 ? '' : 's'} matching “${q}”`,
    limited: (n: number) => `Showing the first ${n}. Search to narrow down.`,
    empty: 'No bookings yet',
    emptyBody: 'Bookings from the calendar and your booking page appear here.',
    noMatch: 'No bookings match',
    noMatchBody: 'Try part of the name, the phone number or the plate number.',
    due: (amount: string) => `${amount} due`,
    depositPending: 'Deposit pending',
    paymentPending: 'Payment pending',
    depositKept: 'Deposit kept',
  },
  booking: {
    newTitle: 'New booking',
    rescheduleTitle: 'Reschedule',
    walkInTitle: 'Walk-in',
    walkInSubtitle: 'Customer is here now · today',
    startNow: 'Start now',
    startNowHint: 'Or pick a free time above',
    service: 'Service',
    duration: 'Duration',
    resource: (label: string) => label,
    any: 'Any available',
    date: 'Date',
    time: 'Time',
    noSlots: 'No free times on this day.',
    noResourcesForService: (label: string) => `No ${label.toLowerCase()}s offer this service yet. Link them in Setup → Services.`,
    otherTime: 'Pick another time',
    slotTakenTitle: 'That slot was just taken',
    slotTakenBody: 'Another booking for this time came in a moment ago. Choose another time.',
    otherTimeHint: 'Any start time, e.g. 10:15',
    outsideHours: 'Allow outside working hours',
    outsideHoursHint: 'Still never double-books',
    customer: 'Customer',
    customerName: 'Name',
    customerPhone: 'Phone',
    address: 'Address',
    addressHint: 'Where the service happens',
    notes: 'Notes from customer',
    internalNotes: 'Internal notes',
    internalNotesHint: 'Only your team sees this',
    walkIn: 'Walk-in (customer is here now)',
    details: 'Booking questions',
    pickSlot: 'Pick a time first',
    create: 'Save booking',
    reschedule: 'Move booking',
    // Detail (O4)
    appointment: 'Appointment',
    when: 'When',
    where: 'Location',
    atBusiness: 'At the business',
    atCustomer: "At customer's location",
    openMaps: 'Open in Google Maps',
    openWaze: 'Open in Waze',
    payment: 'Payment',
    total: 'Total',
    dueOnline: (mode: 'deposit' | 'full') => (mode === 'deposit' ? 'Deposit' : 'Full payment'),
    balance: 'Balance due',
    paid: 'Paid',
    unpaid: 'Unpaid',
    free: 'Free',
    notesTitle: 'Notes',
    source: { web: 'Online', app: 'Added by team', walk_in: 'Walk-in' },
    call: 'Call customer',
    whatsapp: 'WhatsApp customer',
    confirm: 'Confirm',
    checkIn: 'Check in',
    complete: 'Mark completed',
    noShow: 'No-show',
    cancel: 'Cancel booking',
    cancelTitle: 'Cancel booking',
    cancelReason: 'Reason',
    cancelReasonHint: 'e.g. Customer called to cancel',
    reasons: ['Customer asked', 'Didn’t pay', 'We’re closed', 'Double booked'],
    reasonOther: 'Other',
    paidLabel: (what: string, amount: string) => `${what} paid · ${amount}`,
    depositWord: 'Deposit',
    paymentWord: 'Payment',
    keepDeposit: 'Keep deposit',
    keepDepositHint: (policy: boolean) => (policy ? 'Cancelled less than your cut-off before start · your policy' : 'No refund'),
    fullRefund: 'Full refund',
    partialRefund: 'Partial refund',
    partialRefundHint: 'Enter an amount',
    refundAmount: 'Refund amount',
    refundTooLarge: (max: string) => `At most ${max}`,
    refundMethod: 'How you refunded',
    refundMethods: { bank_transfer: 'Bank transfer', duitnow: 'DuitNow', cash: 'Cash' },
    refundNote: 'Refunds are paid by you outside the app. We only record them for your reports.',
    tellCustomer: 'Tell customer on WhatsApp',
    tellCustomerHint: 'Sends cancellation and refund note',
    cancelMessage: (name: string, service: string, when: string, refund: string | null) =>
      `Hi ${name}, your booking for ${service} on ${when} has been cancelled.${refund ? ` We have refunded ${refund}.` : ''}`,
    cancelConfirm: 'Cancel booking',
    keep: 'Keep booking',
    refunded: 'Refunded',
    paidSoFar: 'Paid',
    // H8 timeline / extend
    timeline: 'Timeline',
    events: {
      created: 'Booked',
      confirmed: 'Confirmed',
      paid: 'Paid',
      payment_failed: 'Payment not completed',
      pay_link_sent: 'Payment link sent',
      reminder_sent: 'Reminder sent',
      rescheduled: 'Rescheduled',
      checked_in: 'Checked in',
      completed: 'Completed',
      extended: 'Extended',
      no_show: 'No-show',
      cancelled: 'Cancelled',
      refunded: 'Refund recorded',
      expired: 'Expired (not paid)',
    },
    eventBy: (name: string) => `by ${name}`,
    eventOnline: 'Booking page',
    eventCustomer: 'Customer',
    eventSystem: 'Automatic',
    completedNext: 'Tap below when they finish',
    extend: (d: string) => `Extend ${d}`,
    extended: 'Booking extended',
    noShowAfterCheckIn: "No-show isn't available after check-in.",
    awaitingPayment: 'Awaiting payment',
    releasedIn: (mmss: string) => `slot released in ${mmss} if unpaid`,
    payLinkSent: (time: string) => `Pay link sent ${time}`,
    resendPayLink: 'Resend pay link',
    payLinkMessage: (name: string, amount: string, service: string, when: string, url: string) =>
      `Hi ${name}, please pay ${amount} to confirm your ${service} booking on ${when}: ${url}`,
    recordPayment: 'Record payment',
    amountReceived: 'Amount received',
    method: 'Method',
    methods: { cash: 'Cash', duitnow_qr: 'DuitNow QR', card: 'Card', bank_transfer: 'Bank transfer' },
    reference: 'Reference (optional)',
    savePayment: 'Save payment',
    paymentSaved: 'Payment recorded',
    holdReleased: 'Not paid in time — slot released',
    noShowTitle: 'Mark as no-show?',
    noShowBody: 'The customer did not come. This frees the time.',
    cancelledReason: (r: string) => `Reason: ${r}`,
    status: {
      pending: 'Pending',
      confirmed: 'Confirmed',
      checked_in: 'Checked in',
      completed: 'Completed',
      cancelled: 'Cancelled',
      no_show: 'No-show',
    },
    paymentStatus: { not_required: 'Pay at venue', unpaid: 'Unpaid', paid: 'Paid', refunded: 'Refunded' },
  },
  /** D10 customers list · D11 customer profile (Phase 6). */
  customers: {
    title: 'Customers',
    count: (n: number) => (n === 1 ? '1 customer' : `${n} customers`),
    add: 'Add customer',
    search: 'Search name or mobile',
    clear: 'Clear search',
    filters: { all: 'All', regulars: 'Regulars', new: 'New', no_shows: 'No-shows' },
    tags: { regular: 'Regular', new: 'New' },
    noShowsTag: (n: number) => `${n} no-shows`,
    visits: (n: number) => (n === 1 ? '1 visit' : `${n} visits`),
    lastVisit: (d: string) => `last ${d}`,
    noVisits: 'No visits yet',
    noPhone: 'No mobile',
    empty: 'No customers yet',
    emptyBody: 'Customers are added automatically when they book.',
    noMatch: 'No customers found',
    noMatchBody: 'Try another name or mobile number.',
    loadMore: 'Show more',
    // D11
    profileTitle: 'Customer',
    call: 'Call',
    whatsapp: 'WhatsApp',
    book: 'Book',
    statVisits: 'Visits',
    statSpent: 'Spent',
    statNoShows: 'No-shows',
    notes: 'Notes',
    noNotes: 'No notes yet. Add preferences, e.g. favourite court or time.',
    edit: 'Edit',
    upcoming: 'Upcoming',
    history: 'History',
    noHistory: 'No past bookings',
    erase: "Delete this customer's data (PDPA request)",
    eraseTitle: "Delete this customer's data?",
    eraseBody: (name: string) =>
      `${name}'s name, mobile, email and notes are removed, and so are the address and answers on their bookings. Past bookings and payments stay in your reports as "Deleted customer". This cannot be undone.`,
    eraseConfirm: 'Delete data',
    erased: 'Customer data deleted',
    // Add / edit sheet
    editTitle: 'Edit customer',
    name: 'Name',
    mobile: 'Mobile',
    email: 'Email (optional)',
    notesLabel: 'Notes (only you see these)',
    save: 'Save',
    saved: 'Saved',
    added: 'Customer added',
    exists: 'This mobile number belongs to an existing customer.',
    openExisting: 'Open that customer',
  },
  /** Staff app (Phase 6): S1 today, S2 job, G2 schedule, G3 profile. */
  staffApp: {
    todayTitle: "Today's bookings",
    todaySub: (date: string, business: string) => `${date} · ${business}`,
    countToday: (n: number) => `${n} today`,
    emptyToday: 'Nothing booked for you today',
    emptyTodayBody: 'New bookings on your schedule show up here.',
    noResource: 'Not linked to a schedule yet',
    noResourceBody: 'Ask the business owner to link your login to a resource in Setup → Resources.',
    next: 'Next',
    nextIn: (when: string) => `Next · in ${when}`,
    nowOn: 'Now',
    inProgress: 'In progress',
    travel: (min: string) => `${min} travel buffer`,
    checkInArrived: "I've arrived · check in",
    openJob: 'Open job',
    waze: 'Waze',
    maps: 'Google Maps',
    whatsapp: 'WhatsApp customer',
    // S2
    checkedInAt: (time: string) => `checked in ${time}`,
    customer: 'Customer',
    noPhone: 'No phone number',
    location: 'Location',
    details: 'Details',
    resultNotes: 'Result notes',
    resultNotesHint: 'What you found or agreed. Saved to the booking.',
    saveNotes: 'Save notes',
    notesSaved: 'Notes saved',
    photos: (n: number) => `Photos (${n})`,
    photosHint: 'Only you and the business see these',
    addPhoto: 'Add photo',
    takePhoto: 'Take photo',
    choosePhoto: 'Choose from library',
    photoAdded: 'Photo added',
    deletePhotoTitle: 'Delete this photo?',
    deletePhotoBody: 'It is removed from the booking.',
    deletePhoto: 'Delete',
    cameraDenied: 'Allow camera access in your phone settings to take photos.',
    payment: 'Payment',
    toCollect: 'To collect',
    paidInFull: 'Paid in full',
    noPayment: 'No payment needed',
    markCompleted: 'Mark completed',
    noShow: 'No-show',
    completedToast: 'Marked completed',
    checkedInToast: 'Checked in',
    // G2
    scheduleTitle: 'My schedule',
    prevWeek: 'Previous week',
    nextWeek: 'Next week',
    today: 'today',
    noBookings: 'No bookings',
    dayOff: 'Day off',
    closed: 'Closed',
    // G3
    myHours: 'My working hours',
    hoursNote: 'Your hours are set by the business owner. Ask them to change.',
    noHours: 'No working hours set yet',
    timeOffTitle: 'Upcoming time off',
    notifications: 'Notifications',
    notifyNew: 'New bookings for me',
    notifyChanges: 'Cancellations & payment problems',
    notifySummary: 'Daily summary in the morning',
    notifyNote: 'Turning these off only stops phone alerts.',
    mobile: 'Mobile',
    email: 'Email',
  },
  reports: {
    periods: { today: 'Today', week: 'This week', month: 'This month' },
    previous: 'Previous period',
    next: 'Next period',
    revenue: 'Revenue',
    bookings: 'Bookings',
    noShowRate: 'No-show rate',
    utilisation: (label: string) => `${label} utilisation`,
    vs: { today: 'yesterday', week: 'last week', month: 'last month' },
    vsBefore: { today: 'the day before', week: 'the week before', month: 'the month before' },
    pct: (n: number) => `${n > 0 ? '+' : ''}${n}%`,
    delta: (n: number) => (n > 0 ? `+${n}` : String(n)),
    trend: (change: string, vs: string) => `${change} vs ${vs}`,
    noShows: (n: number) => (n === 1 ? '1 no-show' : `${n} no-shows`),
    hoursBooked: (booked: string, open: string) => `${booked} of ${open} h booked`,
    noHours: 'No opening hours',
    perDay: 'Bookings per day',
    perDayNote: 'Lighter bars include bookings still to come.',
    summary: 'Summary',
    statuses: {
      upcoming: 'Upcoming',
      checkedIn: 'Checked in',
      completed: 'Completed',
      noShow: 'No-shows',
      cancelled: 'Cancelled',
    },
    topServices: 'Top services',
    byResource: (label: string) => `Utilisation by ${label.toLowerCase()}`,
    money: 'Payments',
    collected: 'Collected',
    refunded: 'Refunded',
    moneyNote: 'Revenue is the value of bookings (no-shows left out). Collected is money recorded in the app in this period.',
    customers: 'Customers',
    newCustomers: 'New',
    returning: 'Returning',
    empty: 'No bookings in this period',
    emptyBody: 'Share your booking link to start getting bookings.',
  },
  placeholder: {
    calendar: 'Day and week calendar by resource arrives in Phase 3.',
    setup: 'Services, resources and working hours arrive in Phase 2.',
    staffToday: "Your bookings for today will appear here.",
    schedule: 'Your upcoming schedule will appear here.',
  },
} as const;

export const t = en;
